name: project
version: '1.0-SNAPSHOT'
main: com.hanabi.project.Project
api-version: '1.20'

commands:
  dice:
   description:  さいころを回す

  mc:
    description: 丁半を行う

  bank:
    description:  所持金を見る

  getmoney:
    description: お金を入手する








